# theme
theme: jekyll-theme-cayman

# theme config
show_downloads: false

# site info
title: Gaymers.GG
description: Gaymers.GG is a Discord server for LGBTQ+ gamers. We’re a welcoming community with colourful members from all over the world.
footer: Gaymers.GG is a community effort and its success is owed to our lovely contributors